---
default:
    - debug: true
      open: public/index-debug.html
      extra: -use-network=false -static-link-runtime-shared-libraries
    
library-path:
    - source/swc

source-path:
    - source/libs
    - source/classes
    
applications:
    - class: source/classes/${TM_NEW_FILE_BASENAME}.as
      output: public/${TM_NEW_FILE_BASENAME}.swf      
# asdoc:
#     - title: "My ActionScript project"
#       footer: "My ActionScript project footer"
#       output: docs/
#       exclude-dirs: 
#         - source/classes/com/greensock/
#         - source/classes/br/com/stimuli/
